version: '3.1'
services:
  app:
    container_name: app-springboot-fota
    image: app-springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
      - "52924:52924"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fotadb